Add section Hero
AndreiGutnik/TheWatchSpot pull request #2
Opened 2023-04-20 18:02 UTC by vladikon70

2023-04-21 09:28 UTC, OleksiiMinnikov reviewed
Мобайл
padding-top: 122px, должен 69 до раздела меню

hero-text-bottom
Не хватает margin-top: 40px;

Планшет 
padding-top: 148px, должен 80 до раздела меню

Пк
Нет фона  по бокам.

2023-04-21 15:23 UTC, AndreiGutnik requested changes
коментарі в слаку

2023-04-23 12:27 UTC, AndreiGutnik approved these changes

2023-04-23 16:15 UTC, OleksiiMinnikov approved these changes

2023-04-23 16:49 UTC, closed without merging