images
AndreiGutnik/TheWatchSpot pull request #3
Opened 2023-04-21 12:28 UTC by Volodimir97

2023-04-21 12:51 UTC, AndreiGutnik requested changes
зображення, які однакові за розміром, дублювати непотрібно. Прибрати папки dest, tabl, mob, лишити лише розбивку по секціях.
desctop, tablet, mobile додати як префікс до назви файлу, лише, якщо відрізняються розміри.
Всі зображення повинні знаходитися в папці images в проекті, а не бути окремою.

2023-04-21 12:55 UTC, AndreiGutnik commented
svg-спрайт помістити в корегь папки images

2023-04-21 16:35 UTC, Yuliia001 reviewed
Перемісти папку images в основну папку проекту в scs.

 І погоджуюсь з Андрієм, краще створити в папці images папки під кожну секцію, де є зображення і додати картинки відповідно для mobile/tablet/desktop. Так той хто працює над певною секцією, зможе працювати з однією папкою.
Для зручності назви картинки так
watch1@1x-mob.jpg
watch1@1x-tab.jpg
watch1@1x.jpg
watch1@2x-mob.jpg
watch1@2x-tab.jpg
watch1@2x.jpg

Спрайт icons.svg додай також в папку images

2023-04-21 16:37 UTC, Yuliia001 requested changes
коментар написала вище

2023-04-22 07:51 UTC, Yuliia001 reviewed
Видали дублювання розширення зображень і у гіфки, тобто це
watch1@1x-dest.jpg.jpg

2023-04-22 11:00 UTC, AndreiGutnik requested changes
коментарі в слаку

2023-04-22 11:33 UTC, AndreiGutnik requested changes
треба оптимізувати спрайт

2023-04-22 15:01 UTC, AndreiGutnik approved these changes
ок

2023-04-22 15:56 UTC, Yuliia001 approved these changes

2023-04-22 16:09 UTC, merged