footer
AndreiGutnik/TheWatchSpot pull request #9
Opened 2023-04-22 20:56 UTC by Mykhailo112

2023-04-23 09:07 UTC, OleksiiMinnikov approved these changes

2023-04-24 08:21 UTC, AndreiGutnik requested changes
коментари в слаці

2023-04-24 12:09 UTC, Yuliia001 requested changes
По мобілці:
- з посилання  address прибери font-size: 14px; 
 - з діва .logo-div прибери margin-bottom: 40px;  і постав його на .footer-logo-nav-div( вони є сусідніми елементами)
 - .footer-soc-link зайві стилі 
   flex-direction: row, паддінги і гап.
- .footer-soc-list прибери марджин , він не сусідній єлемент з .footer-down-list. Постав його на дів .footer-logo-soc-div

2023-04-24 16:53 UTC, Yuliia001 approved these changes
approved

2023-04-24 17:53 UTC, AndreiGutnik approved these changes
ок

2023-04-24 17:53 UTC, merged